"""Initial setup with batch

Revision ID: e56d057f9f72
Revises: 
Create Date: 2026-02-07 22:44:50.130687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56d057f9f72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False, server_default='user'))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True, server_default='false'))
        batch_op.add_column(sa.Column('trial_credits', sa.Integer(), nullable=True, server_default='3'))
        batch_op.add_column(sa.Column('last_credit_reset', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_credit_reset')
        batch_op.drop_column('trial_credits')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('role')
    # ### end Alembic commands ###
